import type { ModuleData, PhaseInfo } from './types';

export const PHASES: PhaseInfo[] = [
  {
    id: 'phase1',
    name: 'Neural & Architecture Foundations',
    range: 'Modules 001 – 014',
    description: 'From biological perceptrons to auto-grad, CNNs, RNNs, and full Transformer Attention architectures.',
    badgeClass: 'badge-phase1',
    accentColor: '#38bdf8'
  },
  {
    id: 'phase2',
    name: 'Efficient LLM Architectures & Alignment',
    range: 'Modules 015 – 025',
    description: 'KV-Cache, FlashAttention, DeepSeek MLA, PEFT/LoRA, DPO Preference Tuning, and Vector Indexing.',
    badgeClass: 'badge-phase2',
    accentColor: '#a78bfa'
  },
  {
    id: 'phase3',
    name: 'Agentic Loop Primitives & Swarms',
    range: 'Modules 026 – 035',
    description: 'ReAct agent loops, multi-agent debate, agent memory, MCP protocol, PPO alignment, and SWE benchmarks.',
    badgeClass: 'badge-phase3',
    accentColor: '#34d399'
  },
  {
    id: 'phase4',
    name: 'Advanced Scaling, Multimodal & Capstone',
    range: 'Modules 036 – 050',
    description: 'Graph RAG, Vision-Language VLMs, MCTS Tree Search, P2P Swarms, AI Gateways, and Autonomous AI Engineer Capstone.',
    badgeClass: 'badge-phase4',
    accentColor: '#fbbf24'
  }
];

export const MODULES: ModuleData[] = [
  // --- PHASE 1 ---
  {
    id: '001',
    title: 'Perceptron From Scratch',
    subtitle: 'The Atomic Unit of Neural Networks',
    phaseId: 'phase1',
    phaseName: 'Neural & Architecture Foundations',
    difficulty: 'beginner',
    estimatedMinutes: 90,
    testCount: 16,
    prerequisites: [],
    topics: ['Binary Linear Classifier', 'Step Activation', 'Perceptron Learning Rule', 'XOR Limitation'],
    overview: 'The foundational building block of artificial neural networks. Demonstrates how a single linear decision boundary learns linearly separable logic functions.',
    mentalModelSummary: 'A balance scale weighing incoming numerical signals against a threshold bias to fire a 0/1 signal.',
    mathHighlight: 'y = \\text{step}(w^T x + b) \\quad \\text{where } w_{t+1} = w_t + \\eta (y - \\hat{y}) x',
    codeSnippet: 'def predict(self, x):\n    return 1 if (np.dot(x, self.weights) + self.bias) >= 0 else 0',
    engineeringChallengeTitle: 'Implement Perceptron Convergence Proof Verification',
    engineeringChallengeGoal: 'Prove that the learning algorithm terminates in finite steps for linearly separable datasets.',
    sources: [{ title: 'The Perceptron', authors: 'Rosenblatt', year: 1958 }]
  },
  {
    id: '002',
    title: 'Multilayer Perceptron & Activations',
    subtitle: 'Overcoming Non-Linear Decision Boundaries',
    phaseId: 'phase1',
    phaseName: 'Neural & Architecture Foundations',
    difficulty: 'beginner',
    estimatedMinutes: 120,
    testCount: 16,
    prerequisites: ['001'],
    topics: ['Hidden Layers', 'Sigmoid & ReLU', 'XOR Resolution', 'Feedforward Pass'],
    overview: 'Stacking single perceptrons with non-linear activation functions to create universal function approximators capable of solving non-linear problems like XOR.',
    mentalModelSummary: 'Folding paper space so non-separable points can be sliced cleanly by a straight line.',
    mathHighlight: 'h = \\sigma(W_1 x + b_1), \\quad y = \\sigma(W_2 h + b_2)',
    codeSnippet: 'def relu(x):\n    return np.maximum(0, x)',
    engineeringChallengeTitle: 'Build a Multi-Class Softmax Classifier',
    engineeringChallengeGoal: 'Extend feedforward MLPs to multi-class classification with numerical stability tricks.',
    sources: [{ title: 'Learning representations by back-propagating errors', authors: 'Rumelhart et al.', year: 1986 }]
  },
  {
    id: '003',
    title: 'Automatic Differentiation & Backprop',
    subtitle: 'Computation Graphs and Chain Rule Derivative Tracking',
    phaseId: 'phase1',
    phaseName: 'Neural & Architecture Foundations',
    difficulty: 'intermediate',
    estimatedMinutes: 150,
    testCount: 16,
    prerequisites: ['001', '002'],
    topics: ['Reverse-Mode Autodiff', 'Computation Graph Node', 'Jacobian Vector Products', 'Gradient Flow'],
    overview: 'The mathematical core of modern deep learning frameworks. Builds an engine that constructs a computational graph during the forward pass and evaluates exact gradients during reverse pass.',
    mentalModelSummary: 'Recording every arithmetic operation on a tape so you can play it backward to compute exact sensitivity.',
    mathHighlight: '\\frac{\\partial L}{\\partial x} = \\sum_{y \\in \\text{Children}(x)} \\frac{\\partial L}{\\partial y} \\frac{\\partial y}{\\partial x}',
    codeSnippet: 'def backward(self):\n    for node in reversed(topological_sort):\n        node._backward()',
    engineeringChallengeTitle: 'Build Micrograd Derivative Engine',
    engineeringChallengeGoal: 'Create a custom autograd scalar engine supporting + - * / exp log and power operations.',
    sources: [{ title: 'Automatic Differentiation in Machine Learning', authors: 'Baydin et al.', year: 2018 }]
  },
  {
    id: '004',
    title: 'Gradient Descent Optimizers',
    subtitle: 'SGD, Momentum, RMSprop, Adam, and AdamW',
    phaseId: 'phase1',
    phaseName: 'Neural & Architecture Foundations',
    difficulty: 'intermediate',
    estimatedMinutes: 120,
    testCount: 16,
    prerequisites: ['003'],
    topics: ['Stochastic Gradient Descent', 'Momentum Vector', 'Adaptive Learning Rates', 'Weight Decay Decoupling'],
    overview: 'Explores optimization algorithms used to train neural networks, from basic SGD to adaptive moment estimation (AdamW) with weight decay.',
    mentalModelSummary: 'A heavy marble rolling down a foggy mountain valley, gaining momentum on smooth slopes and braking on bumpy terrain.',
    mathHighlight: 'm_t = \\beta_1 m_{t-1} + (1-\\beta_1) g_t, \\quad v_t = \\beta_2 v_{t-1} + (1-\\beta_2) g_t^2',
    codeSnippet: 'm_hat = m / (1 - beta1**t)\nv_hat = v / (1 - beta2**t)\nw -= lr * m_hat / (np.sqrt(v_hat) + eps)',
    engineeringChallengeTitle: 'Build AdamW Optimizer from Scratch',
    engineeringChallengeGoal: 'Implement AdamW with decoupled weight decay and verify convergence on noisy loss surfaces.',
    sources: [{ title: 'Adam: A Method for Stochastic Optimization', authors: 'Kingma & Ba', year: 2014 }]
  },
  {
    id: '010',
    title: 'Scaled Dot-Product & Self-Attention',
    subtitle: 'The Attention Mechanism that Powered the LLM Revolution',
    phaseId: 'phase1',
    phaseName: 'Neural & Architecture Foundations',
    difficulty: 'advanced',
    estimatedMinutes: 180,
    testCount: 16,
    prerequisites: ['003', '004'],
    topics: ['Query Key Value Projections', 'Softmax Normalization', 'Causal Masking', 'Multi-Head Splitting'],
    overview: 'The fundamental building block of Transformers. Computes dynamic pairwise similarity weights between elements in a sequence.',
    mentalModelSummary: 'A library database search where a Query matches against item Keys to compute a weighted blend of Value content.',
    mathHighlight: '\\text{Attention}(Q, K, V) = \\text{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V',
    codeSnippet: 'scores = np.dot(Q, K.T) / np.sqrt(d_k)\nattn = softmax(scores + mask)\noutput = np.dot(attn, V)',
    engineeringChallengeTitle: 'Build Multi-Head Attention Module',
    engineeringChallengeGoal: 'Implement parallel multi-head attention with causal masking support for auto-regressive decoding.',
    sources: [{ title: 'Attention Is All You Need', authors: 'Vaswani et al.', year: 2017 }]
  },
  {
    id: '011',
    title: 'Full Transformer Encoder-Decoder',
    subtitle: 'Complete Sequence-to-Sequence Architecture',
    phaseId: 'phase1',
    phaseName: 'Neural & Architecture Foundations',
    difficulty: 'advanced',
    estimatedMinutes: 210,
    testCount: 17,
    prerequisites: ['010'],
    topics: ['Encoder Blocks', 'Decoder Cross-Attention', 'Residual Connections', 'LayerNorm Position'],
    overview: 'Combines Transformer encoder and decoder layers into a sequence-to-sequence translation and generation model from scratch.',
    mentalModelSummary: 'An encoder reading a sentence into a rich contextual canvas, while a decoder paints the output word by word while checking the canvas.',
    mathHighlight: 'x_{l+1} = \\text{LayerNorm}(x_l + \\text{MultiHeadAttention}(x_l))',
    codeSnippet: 'class TransformerDecoderLayer:\n    def forward(self, x, enc_output):\n        x = x + self.self_attn(self.norm1(x))\n        x = x + self.cross_attn(self.norm2(x), enc_output)',
    engineeringChallengeTitle: 'Build Full Mini-Transformer Model',
    engineeringChallengeGoal: 'Train a 2-layer Transformer on toy sequence reversal task with 100% accuracy.',
    sources: [{ title: 'Attention Is All You Need', authors: 'Vaswani et al.', year: 2017 }]
  },

  // --- PHASE 2 ---
  {
    id: '015',
    title: 'KV-Cache & Grouped-Query Attention',
    subtitle: 'Optimizing Inference Memory for Long Generation',
    phaseId: 'phase2',
    phaseName: 'Efficient LLM Architectures & Alignment',
    difficulty: 'advanced',
    estimatedMinutes: 180,
    testCount: 16,
    prerequisites: ['010', '011'],
    topics: ['KV-Cache Rollout', 'Grouped-Query Attention (GQA)', 'Multi-Query Attention (MQA)', 'Memory Bandwidth Optimization'],
    overview: 'Eliminates redundant computation during auto-regressive generation by caching past Key and Value tensor representations.',
    mentalModelSummary: 'A scratchpad keeping memory of past words so you only calculate attention for the new single token being typed.',
    mathHighlight: 'K_{\\text{cached}} = [K_{\\text{past}} \\,;\\, K_{\\text{new}}], \\quad V_{\\text{cached}} = [V_{\\text{past}} \\,;\\, V_{\\text{new}}]',
    codeSnippet: 'self.k_cache[:, :, current_pos:current_pos+seq_len, :] = k_new\nattn_out = compute_gqa(q_new, self.k_cache, self.v_cache)',
    engineeringChallengeTitle: 'Build a Rolling KV-Cache Inference Engine',
    engineeringChallengeGoal: 'Implement GQA with sliding KV-cache and measure 5x speedup during auto-regressive text generation.',
    sources: [{ title: 'GQA: Training Generalized Multi-Query Transformer Models', authors: 'Ainslie et al.', year: 2023 }]
  },
  {
    id: '018',
    title: 'FlashAttention Memory-Aware GPU Tiling',
    subtitle: 'Exact Attention without O(N²) Memory Overhead',
    phaseId: 'phase2',
    phaseName: 'Efficient LLM Architectures & Alignment',
    difficulty: 'advanced',
    estimatedMinutes: 240,
    testCount: 16,
    prerequisites: ['010', '015'],
    topics: ['Tiled Attention', 'Online Softmax Trick', 'SRAM vs HBM Bandwidth', 'IO-Aware Algorithm'],
    overview: 'Fuses softmax normalization and attention matrix multiplication into tiled blocks to reduce GPU memory reads and writes from $O(N^2)$ to $O(N)$.',
    mentalModelSummary: 'Cooking a massive meal in tiny frying pans (SRAM) instead of running back and forth to the giant pantry (HBM).',
    mathHighlight: 'm_{new} = \\max(m_{prev}, m_{block}), \\quad d_{new} = d_{prev} e^{m_{prev} - m_{new}} + d_{block} e^{m_{block} - m_{new}}',
    codeSnippet: 'def flash_attn_block(Q_i, K_j, V_j, prev_m, prev_l, prev_acc):\n    # Online softmax update inside tile block\n    pass',
    diagramType: 'dataflow',
    engineeringChallengeTitle: 'Implement Pure Python Online Softmax Tiling',
    engineeringChallengeGoal: 'Verify exact numerical equivalence between standard attention and online tiled FlashAttention.',
    sources: [{ title: 'FlashAttention: Fast and Memory-Efficient Exact Attention', authors: 'Dao et al.', year: 2022 }]
  },
  {
    id: '020',
    title: 'Multi-Head Latent Attention (MLA)',
    subtitle: 'DeepSeek-V3 Low-Rank KV Compression',
    phaseId: 'phase2',
    phaseName: 'Efficient LLM Architectures & Alignment',
    difficulty: 'advanced',
    estimatedMinutes: 210,
    testCount: 16,
    prerequisites: ['015', '018'],
    topics: ['Low-Rank KV Compression', 'Decoupled RoPE Embedding', 'DeepSeek-V3 Architecture', 'KV Latent Vector c_t^KV'],
    overview: 'DeepSeek-V3 landmark attention architecture. Compresses Key and Value states into a low-rank latent vector $c_t^{KV}$ to drastically reduce KV-cache memory during inference.',
    mentalModelSummary: 'Compressing full HD video streams into lightweight zip files that are unpacked on-the-fly during attention computation.',
    mathHighlight: 'c_t^{KV} = W^{DKV} h_t, \\quad K_t^C = W^{UK} c_t^{KV}, \\quad V_t^C = W^{UV} c_t^{KV}',
    codeSnippet: 'c_kv = np.dot(x, W_DKV)  # Low-rank latent compression\nK_c = np.dot(c_kv, W_UK)  # Uncompressed Key projection\nV_c = np.dot(c_kv, W_UV)  # Uncompressed Value projection',
    engineeringChallengeTitle: 'Build DeepSeek MLA Compression Engine',
    engineeringChallengeGoal: 'Achieve 90% KV-cache RAM reduction while maintaining full attention dot-product precision.',
    sources: [{ title: 'DeepSeek-V3 Technical Report', authors: 'DeepSeek AI Team', year: 2024 }]
  },

  // --- PHASE 3 ---
  {
    id: '026',
    title: 'Agentic Loop Primitives',
    subtitle: 'ReAct Trajectories, Tool Selection & POMDP Formulation',
    phaseId: 'phase3',
    phaseName: 'Agentic Loop Primitives & Swarms',
    difficulty: 'advanced',
    estimatedMinutes: 180,
    testCount: 16,
    prerequisites: ['010', '011'],
    topics: ['Perceive-Think-Act Cycle', 'ReAct Trajectory Parsing', 'UCB1 Tool Selection', 'POMDP Agent Math'],
    overview: 'The fundamental loop architecture behind autonomous agents. Bridges static LLMs to active problem solvers using reasoning trace scratchpads and executable tool calls.',
    mentalModelSummary: 'A junior developer at a terminal: reading problem, writing thoughts, invoking commands, checking output, and repeating.',
    mathHighlight: '\\tau = (o_1, t_1, a_1, o_2, t_2, a_2, \\dots), \\quad UCB1_i = \\bar{x}_i + c \\sqrt{\\frac{\\ln N}{n_i}}',
    codeSnippet: 'class ReActAgent:\n    def run(self, task):\n        while not finished and steps < max_steps:\n            thought, action = self.llm_step(history)\n            obs = self.execute_tool(action)\n            history.append(obs)',
    diagramType: 'workflow',
    engineeringChallengeTitle: 'Build a Multi-Tool ReAct Agent Engine',
    engineeringChallengeGoal: 'Build a robust ReAct agent with UCB1 tool priority selection and retry error handling.',
    sources: [{ title: 'ReAct: Synergizing Reasoning and Acting in Language Models', authors: 'Yao et al.', year: 2022 }]
  },
  {
    id: '032',
    title: 'Model Context Protocol (MCP)',
    subtitle: 'Client-Server Standard for Context & Tools',
    phaseId: 'phase3',
    phaseName: 'Agentic Loop Primitives & Swarms',
    difficulty: 'advanced',
    estimatedMinutes: 180,
    testCount: 16,
    prerequisites: ['026', '029'],
    topics: ['JSON-RPC 2.0 Protocol', 'MCP Resources & Prompts', 'Dynamic Tool Discovery', 'Capability Negotiation'],
    overview: 'Anthropic Model Context Protocol standard. Establishes a clean USB-C style client-server protocol for connecting AI models to dynamic tools and data sources.',
    mentalModelSummary: 'The universal USB-C cable for AI models: plug any tool or database server into any LLM client seamlessly.',
    mathHighlight: '\\text{Request} = \\{\\text{jsonrpc}: \\text{"2.0"}, \\text{method}: \\text{"tools/call"}, \\text{params}: \\{\\dots\\}\\}',
    codeSnippet: 'class MCPServer:\n    def handle_request(self, msg):\n        if msg["method"] == "tools/list":\n            return {"tools": [t.to_dict() for t in self.tools]}',
    diagramType: 'sequence',
    engineeringChallengeTitle: 'Build a Dynamic Multi-Server MCP Aggregator Router',
    engineeringChallengeGoal: 'Create an MCP aggregator router that dynamically multiplexes 5 independent MCP tool servers into a single LLM client session.',
    sources: [{ title: 'Model Context Protocol Specification', authors: 'Anthropic', year: 2024 }]
  },

  // --- PHASE 4 ---
  {
    id: '036',
    title: 'Graph RAG & Knowledge Graphs',
    subtitle: 'Multi-Hop Reasoning Across Entity-Relation Networks',
    phaseId: 'phase4',
    phaseName: 'Advanced Scaling, Multimodal & Capstone',
    difficulty: 'advanced',
    estimatedMinutes: 210,
    testCount: 16,
    prerequisites: ['024', '025', '030'],
    topics: ['Entity-Relation Extraction', 'Leiden Community Detection', 'Personalized PageRank', 'Global Summary Querying'],
    overview: 'Overcomes vector-only RAG limitations for global multi-hop queries by extracting structured knowledge graphs and generating community summaries.',
    mentalModelSummary: 'A detective string-board connecting entity pins across hundreds of documents to reveal hidden global relationships.',
    mathHighlight: 'p = d \\cdot M p + (1-d) v, \\quad Q = \\frac{1}{2m} \\sum_{ij} \\left[ A_{ij} - \\frac{k_i k_j}{2m} \\right] \\delta(c_i, c_j)',
    codeSnippet: 'class KnowledgeGraph:\n    def personalized_pagerank(self, seeds, damping=0.85):\n        # Compute PageRank vector from seed entity nodes\n        pass',
    diagramType: 'architecture',
    engineeringChallengeTitle: 'Build Hybrid Vector + Graph RAG Q&A Engine',
    engineeringChallengeGoal: 'Combine vector search with Leiden community detection summaries to score >90% on multi-hop question answering.',
    sources: [{ title: 'From Local to Global: A Graph RAG Approach', authors: 'Edge et al. (Microsoft)', year: 2024 }]
  },
  {
    id: '046',
    title: 'Agentic Planning & Tree Search (MCTS)',
    subtitle: 'Monte Carlo Tree Search and Tree-of-Thoughts for LLMs',
    phaseId: 'phase4',
    phaseName: 'Advanced Scaling, Multimodal & Capstone',
    difficulty: 'advanced',
    estimatedMinutes: 240,
    testCount: 16,
    prerequisites: ['026', '039'],
    topics: ['Tree of Thoughts (ToT)', 'Upper Confidence Bound for Trees (UCT)', 'Rollout Evaluation', 'State Space Backprop'],
    overview: 'Extends linear Chain-of-Thought into tree search problem solving using Monte Carlo Tree Search (MCTS) for complex multi-step reasoning.',
    mentalModelSummary: 'A chess grandmaster evaluating multiple move lines 5 turns ahead before committing to a physical piece movement.',
    mathHighlight: 'UCT(s, a) = Q(s, a) + c \\sqrt{\\frac{\\ln N(s)}{N(s, a)}}',
    codeSnippet: 'class MCTSSearchEngine:\n    def select(self, node):\n        while not node.is_terminal:\n            if not node.is_fully_expanded():\n                return self.expand(node)\n            node = self.best_child(node)',
    diagramType: 'lifecycle',
    engineeringChallengeTitle: 'Build MCTS Code Generation Fixer',
    engineeringChallengeGoal: 'Implement an MCTS tree search planner that fixes complex multi-file bugs by exploring solution trees.',
    sources: [{ title: 'Tree of Thoughts: Deliberate Problem Solving with LLMs', authors: 'Yao et al.', year: 2023 }]
  },
  {
    id: '048',
    title: 'Distributed Agent Swarms & P2P Protocols',
    subtitle: 'Peer-to-Peer Topologies, Gossip & Raft Consensus',
    phaseId: 'phase4',
    phaseName: 'Advanced Scaling, Multimodal & Capstone',
    difficulty: 'advanced',
    estimatedMinutes: 240,
    testCount: 16,
    prerequisites: ['027', '046'],
    topics: ['P2P Mesh Topologies', 'Gossip Protocol Dissemination', 'Raft Consensus Protocol', 'Byzantine Fault Tolerance'],
    overview: 'Scales multi-agent coordination across decentralized peer-to-peer networks without single-point-of-failure centralized supervisors.',
    mentalModelSummary: 'A flock of birds coordinating complex flight patterns using local neighbor communication without a central leader.',
    mathHighlight: 'T_{\\text{gossip}} = O(\\log N), \\quad f < \\frac{N}{3} \\quad (\\text{Byzantine Bound})',
    codeSnippet: 'class RaftConsensusNode:\n    def handle_request_vote(self, candidate_id, term):\n        if term > self.current_term:\n            self.voted_for = candidate_id\n            return True',
    diagramType: 'architecture',
    engineeringChallengeTitle: 'Build Fault-Tolerant Swarm Consensus State Machine',
    engineeringChallengeGoal: 'Simulate a 10-node agent swarm that maintains synchronized state across 30% node failure and network partitions.',
    sources: [{ title: 'In Search of an Understandable Consensus Algorithm (Raft)', authors: 'Ongaro & Ousterhout', year: 2014 }]
  },
  {
    id: '050',
    title: 'Capstone: Autonomous AI Engineer System',
    subtitle: 'End-to-End Autonomous Software Engineer',
    phaseId: 'phase4',
    phaseName: 'Advanced Scaling, Multimodal & Capstone',
    difficulty: 'capstone',
    estimatedMinutes: 300,
    testCount: 16,
    prerequisites: ['041', '046', '048', '049'],
    topics: ['Full System Integration', 'Memory RAG Sandbox Engine', 'Self-Healing Repair Loop', 'Distributed Observability'],
    overview: 'The grand capstone module of the AI Engineering Academy. Integrates memory, RAG, tool execution sandboxing, state DAGs, MCTS planning, and OpenTelemetry tracing into an end-to-end autonomous AI coding engineer.',
    mentalModelSummary: 'An autonomous engineering organization in a box: architect, developer, tester, and manager operating in a synchronized loop.',
    mathHighlight: '\\text{System Score} = w_1 \\cdot \\text{Pass@K} + w_2 \\cdot \\frac{1}{\\text{Cost}} + w_3 \\cdot \\frac{1}{\\text{Latency}}',
    codeSnippet: 'class AutonomousAIEngineer:\n    def solve_issue(self, issue_desc):\n        context = self.rag.retrieve(issue_desc)\n        plan = self.mcts_planner.plan(issue_desc, context)\n        return self.executor.execute_plan(plan)',
    diagramType: 'architecture',
    engineeringChallengeTitle: 'Deploy the Autonomous AI Engineer System',
    engineeringChallengeGoal: 'Run end-to-end autonomous issue resolution across 10 repository bugs with 100% test pass rate and full telemetry tracing.',
    sources: [{ title: 'SWE-agent: Agent-Computer Interfaces for Software Engineering', authors: 'Yang et al.', year: 2024 }]
  }
];
